version: '3'
services:

 alfresco:
  build: ./alfresco
  ports:
      - 8081:8080

 share:
  build: ./share
  ports:
      - 8080:8080

 postgres:
    image: postgres:10.1
    environment:
        - POSTGRES_PASSWORD=alfresco
        - POSTGRES_USER=alfresco
        - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
        - 5432:5432

 solr6:
    build:
      context: ./solr
      args:
        SOLR_HOSTNAME: solr6
        ALFRESCO_HOSTNAME: alfresco
        ALFRESCO_COMMS: none
        ENABLE_SHARDING: "true"
        NUM_SHARDS: "2"
        SHARD_ID: "0"
        SHARD_RANGE: "0-200"
    environment:
        #Solr needs to know how to register itself with Alfresco
        SOLR_ALFRESCO_HOST: "alfresco"
        SOLR_ALFRESCO_PORT: "8080"
        #Alfresco needs to know how to call solr
        SOLR_SOLR_HOST: "solr6"
        SOLR_SOLR_PORT: "8983"
        #Create the default alfresco and archive cores
        SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
        SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
    ports:
        - 8083:8983

 solr6secondary:
    build:
      context: ./solr
      args:
        SOLR_HOSTNAME: solr6secondary
        ALFRESCO_HOSTNAME: alfresco
        ALFRESCO_COMMS: none
        ENABLE_SHARDING: "true"
        NUM_SHARDS: "2"
        SHARD_ID: "1"
        SHARD_RANGE: "201-40000"
    environment:
        #Solr needs to know how to register itself with Alfresco
        SOLR_ALFRESCO_HOST: "alfresco"
        SOLR_ALFRESCO_PORT: "8080"
        #Alfresco needs to know how to call solr
        SOLR_SOLR_HOST: "solr6secondary"
        SOLR_SOLR_PORT: "8983"
        #Create the default alfresco and archive cores
        SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
        SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
    ports:
        - 8084:8983

 libreoffice:
   build: ./libreoffice
